[tool.poetry]
name = "blogcrawler"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = ">3.8"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
